joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

laser_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: laser_joint
